### ISSUE TITLE
Issueベースの開発レビュー依頼

### ISSUE THREAD

**Issue by abusumi** [abusumi/cat-project#34]
# ■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

本アプリは、猫の1日の必要給与量を計算し、飼い主に対して適切なフードの量を提案するツールです。主に、成長期の子猫やフードの変更時に便利で、飼い主が猫の体重や与えるフードに基づいて給与量を自動で計算できる機能を提供します。2種類までのフードを組み合わせて計算でき、都度調整が必要な給与量を簡単に把握できる点が特徴です。また、他のユーザーとフードに関するレビューを共有する機能も備えており、情報交換が可能です。
MVPリリースでは、基本的な給与量計算機能、ユーザー登録機能、ログイン・ログアウト機能、前回の給与量計算の保存機能、フードの評価や「参考になった」ボタンの実装が予定されています。

猫の1日の必要給与量を計算してー提示してくれるサービス。
新しいフード購入時の給与計算、子猫の体重変化が大きい時期等の手助けをを行ってくれるアプリです。
フードのレビューを共有しフードの情報交換を行えます。

# ■1週間辺りの開発に向けられる時間
- 1週間あたり：25時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

# ■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/abusumi/projects/3

# ■MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワードリセット機能
- [ ] オートコンプリート検索機能
- [ ] フード量計算機能
- [ ] フードの評価機能
- [ ] 評価されたフードの検索機能
- [ ] 参考になった(いいね)ボタン機能

# ■MVP後
- [ ] Google認証
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] ファビコンの設定
- [ ] 給与計算機能のメーカー・フード増設
- [ ] 「うちの猫自慢コーナー」の写真投稿掲示板機能
- [ ] 「うちの猫自慢コーナー」のコメント機能
- [ ] 「うちの猫自慢コーナー」のいいね機能
- [ ] 「うちの猫自慢コーナー」のX共有機能とOGP対応

# ■MVPレビュー依頼予定日
予定日：2024年 12月 24日

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

Rails newが完了したらデプロイを行いましょう。（issueを作成して適切な場所に配置しておいてください）

以下、MVPに含めなくても良いかもと思ったカードになります。
- パスワードリセット
- letter_opener_web
- 日本語化対応

**Comment by abusumi** [comment]
レビューありがとうございます。
***

> 以下、MVPに含めなくても良いかもと思ったカードになります。
パスワードリセット
letter_opener_web
日本語化対応
  
上記項目は検討の末MVPリリース後に行うことにいたしました。
ご指摘いただきありがとうございました。
