### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by abusumi** [abusumi/cat-project#57]
## 各種情報
サービスの概要とMVPで検証する事柄：本アプリは、猫の1日の必要給与量を計算し、飼い主に対して適切なフードの量を提案するツールです。主に、成長期の子猫やフードの変更時に便利で、飼い主が猫の体重や与えるフードに基づいて給与量を自動で計算できる機能を提供します。他のユーザーとフードに関するレビューを共有する機能も備えており、情報交換が可能です。

### MVPで検証する事柄
- 未ログインで使用できる機能
- [x] フードが選択できるか
- [x] フード計算結果が表示されるか
- [x] マイページに保存が選択されるとログインページに遷移するか
- [x] 「再計算する」をクリックするとトップページ(1日の給与量を計算する)ページに遷移するか
- [x] 「cat food mate」をクリックするとトップページ(1日の給与量を計算する)ページに遷移するか
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] ログアウト機能

- ログイン後に使用できる機能
- [x] 計算結果がマイページに保存できるか

サービス名：cat food mate
サービスURL：https://cat-project-dggr.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

[README_Pull request](https://github.com/abusumi/cat-project/pull/1)
- [x] 給与量計算機能（有名メーカーのみ）
- [x] ユーザー登録機能
- [x] ログイン、ログアウト機能
- [x] 前回給与計算結果の保存
- [ ] フードの評価機能：レーディング
- [ ] フードの評価機能の「参考になった」ボタン

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。

MVPリリース時の最低限の機能は実装できていると判断し下記は本リリースで実装予定です。
- フードをメーカーで絞り込む
- サブフードの登録・合わせた計算機
- アプリの使い方説明欄
- フードの評価機能(レーディング)
- フードの評価機能の「参考になった」ボタン
- 評価済みのフード一覧ページ
- 評価済みのフード一覧にリンクを紐付け

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有してください。

### トップ画面
![Image](https://github.com/user-attachments/assets/4388cef5-0ee3-42e4-b73e-3efc69624222)

### 未ログイン時のメニューバー
![Image](https://github.com/user-attachments/assets/6b7ce62c-3e40-484e-bb40-80c98f1f4b7f)

### ログイン後のメニューバー
![Image](https://github.com/user-attachments/assets/9e1ec077-2d45-46d0-a11f-88630e95e1e1)

### 計算機入力
![Image](https://github.com/user-attachments/assets/680d3075-0d27-469f-b521-d6c1d6e2a7d4)

### 計算結果表示
![Image](https://github.com/user-attachments/assets/f7cc69b8-65c9-46b0-992a-01d2da5fc8ec)

### 計算結果保存
![Image](https://github.com/user-attachments/assets/4f907587-05da-431d-8fd4-7ad8e6626f57)

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
